In [1]:
import numpy as np

In [2]:
def get_loop_break_points(n_loops):
    first_val = 1
    num_in_loop = 8 * np.arange(n_loops)
    last_in_loop = first_val + np.cumsum(num_in_loop)
    return last_in_loop

In [3]:
get_loop_break_points(6)

array([  1,   9,  25,  49,  81, 121])

In [4]:
def get_loop_midpoints(last_val, iloop):
    return np.linspace(last_val-7*iloop, last_val-iloop, 4, dtype=np.int32)

In [5]:
get_loop_midpoints(25, 2)

array([11, 15, 19, 23])

In [6]:
def problem03a(number):
    n_loop = int((np.ceil(np.sqrt(number)))/2)
    last_in_loop = (2 * n_loop + 1)**2
    loop_midpoints = get_loop_midpoints(last_in_loop, n_loop)
    dist_to_middle = np.min(np.abs(number - loop_midpoints))
    dist_to_center = dist_to_middle + n_loop
    return dist_to_center

In [7]:
problem03a(1)

0

In [8]:
problem03a(12)

3

In [9]:
problem03a(23)

2

In [10]:
problem03a(1024)

31

In [11]:
problem03a(325489)

552

In [57]:
def problem03b(stop_val=325489):
    spiral = np.zeros([5, 5], np.uint32)
    ind = np.array([2, 2], dtype=np.uint16)
    spiral[ind[0], ind[1]] = 1
    rep = 0
    n_steps = 0
    sign = 1
    while True:
        if rep % 2 == 0:
            row_or_col = 1
            n_steps += 1
            if rep % 4 == 0:
                spiral = np.pad(spiral, [[1, 1,], [1, 1]], 'constant')
                ind += 1
        else:
            row_or_col = 0
            sign *= -1
        for step in range(n_steps):
            ind[row_or_col] += sign
            row, col = ind[0], ind[1]
            #print(row, col)
            spiral[row, col] = np.sum(spiral[row-1:row+2, col-1:col+2])
            current_val = spiral[row, col]
            if current_val > stop_val:
                print('Finished! Current value is', current_val)
                return
        rep += 1
            #print(spiral)


In [15]:
vals = np.array([1, 1, 2, 4, 5, 10, 11, 23, 25, 26, 54, 57, 59, 122, 133, 142, 147, 304, 330, 351, 362, 747, 806])
np.diff(vals)

array([  0,   1,   2,   1,   5,   1,  12,   2,   1,  28,   3,   2,  63,
        11,   9,   5, 157,  26,  21,  11, 385,  59])

In [59]:
problem03b()

('Finished! Current value is', 330785)
